# .github/workflows/scrape.yml
name: Scrape

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.40.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraping script
        run: python scrape.py

      - name: Check folder exists
        run: |
          if [ ! -d "period" ]; then
            echo "Error: 'period/' folder not found!"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: period_results
          path: period/
